---
services:
  robot-description:
    build:
      network: host
      context: ../
      dockerfile: container/Dockerfile
      args:
        base_image: ${REGISTRY_BASE:?}/robotnik/ros
        image_base_version: ${IMAGE_BASE_VERSION:?}
        ros_distro: ${DOCKER_ROS_DISTRO:?}
        version: ${VERSION:?}
        ros_mirror: ${ROS_MIRROR:?}
        alpine_version: 3.17.5
      tags:
        - registry.robotnik.ws/library/robot-description:humble-${VERSION:?}
        - registry.robotnik.ws/library/robot-description:humble-latest
