/**:
  controller_manager:
    ros__parameters:
      use_sim_time: true
      update_rate: 100  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_state_controller:
        type: joint_state_controller/JointStateController


  joint_state_broadcaster:
    ros__parameters:
      use_sim_time: true
      publish_rate: 200

  joint_state_controller:
    ros__parameters:
      use_sim_time: true
      publish_rate: 200