<?xml version="1.0"?>
<robot name="wheel"
	xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="$(find robot_description)/urdf/wheels/rubber_wheel/gazebo/rubber_wheel.transmission.xacro"/>
	<xacro:include filename="$(find robot_description)/urdf/wheels/rubber_wheel/gazebo/rubber_wheel.gazebo.xacro"/>


	<xacro:property name="M_PI" value="3.1415926535897931" />
	<!-- Wheels -->
	<xacro:property name="wheel_radius" value="0.0762" />
	<xacro:property name="wheel_height" value="0.025" />
	<xacro:property name="wheel_mass" value="1" />
	<!-- in kg-->


	<xacro:macro name="cylinder_inertia" params="m r h">
		<inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
				  iyy="${m*r*r/2}" iyz = "0"
				  izz="${m*(3*r*r+h*h)/12}" />
	  </xacro:macro>

	<xacro:macro name="rubber_wheel" params="robot_id parent *origin hq">

		<!--WHEEL TIRE -->
		<joint name="${robot_id}_wheel_joint" type="continuous">
			<parent link="${parent}"/>
			<child link="${robot_id}_wheel_link"/>
			<xacro:insert_block name="origin" />
			<axis xyz="0 1 0" rpy="0 0 0" />
			<limit effort="100" velocity="100"/>
			<joint_properties damping="0.0" friction="0.0"/>
		</joint>

		<link name="${robot_id}_wheel_link">
			<visual>
				<!-- HIGH RESOLUTION WHEELS -->
				<!-- LOW RESOLUTION WHEELS -->
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_height}" radius="${wheel_radius}" />
				</geometry>
			</visual>

			<collision>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_height}" radius="${wheel_radius}" />
				</geometry>
			</collision>
			<inertial>
				<mass value="${wheel_mass}" />
				<origin xyz="0 0 0" rpy="${M_PI} 0 0" />
				<xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}" />
			</inertial>
		</link>

		<joint name="${robot_id}_wheel_tire_joint" type="fixed">
			<parent link="${robot_id}_wheel_link"/>
			<child link="${robot_id}_wheel_tire_link"/>
			<origin xyz="0 0 0" rpy="0 0 0" />
		</joint>

		<link name="${robot_id}_wheel_tire_link">
			<visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_height + 0.001}" radius="${wheel_radius * 0.92}" />
				</geometry>
			</visual>
		</link>


		<xacro:rubber_wheel_transmission robot_id="${robot_id}" />
		<xacro:rubber_wheel_gazebo robot_id="${robot_id}" />


	</xacro:macro>

</robot>
